ORGANISMS = 150

INPUTS = 6
OUTPUTS = 1
C1 = 1.0
C2 = 1.0
C3 = 0.2
DELTA_T = 1.5  # New species threshold

ACTIVATION_THRESHOLD = 0.5


DISABLE_INHERITED_GENE_CHANCE = 0.75
CROSSOVER_CHANCE = 0.75

# MUTATION RATES
WEIGHT_MUTATION_RATE = 0.9
CONNECTION_MUTATION_RATE = 0.3
NEURON_MUTATION_RATE = 0.03
CONNECTION_WEIGHT_MUTATION_RATE = 0.8
NEW_WEIGHT_MUTATION_RATE = 0.1



IMPROVEMENT_THRESHOLD = 5.0
ROUNDS_BEFORE_CULLING = 15
RANK_SELECTION_CUTOFF = 20
