ORGANISMS = 150
RANK_CUTOFF = int(ORGANISMS / 2)
INPUTS = 4
OUTPUTS = 1
C1 = 0.4
C2 = 0.4
C3 = 1.0
DELTA_T = 3  # New species threshold

ACTIVATION_THRESHOLD = 0.5

WEIGHT_MUTATION_RATE = 0.5
CONNECTION_MUTATION_RATE = 0.1
NEURON_MUTATION_RATE = 0.01
